<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxBXl8N\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxBXl8N/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCxBXl8N.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCxBXl8N\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCxBXl8N\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CxBXl8N',
    'container.build_id' => '1be4b6fa',
    'container.build_time' => 1539184204,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxBXl8N');
